### ISSUE TITLE
Question: How do we install this? Couldn't figure it out

### ISSUE THREAD

**Issue by L-E-0-N** [ItsEcholot/ha-paperless-ng-sensor#2]
Nevermind, fixed the installation. Only the integration is also through this error at me:

paperless_ng: Error on device update!

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/config/custom_components/paperless_ng/sensor.py", line 144, in async_update
    self.get_todo_documents, todo_tag_obj.get("id")
AttributeError: 'NoneType' object has no attribute 'get'

Any idea how I can fix this?

**Comment by ItsEcholot** [comment]
This is probably related to #1.
I will try to find some time this weekend to rewrite & fix this integration.

**Comment by Ionshard** [comment]
I was able to install this as a custom repository for hacs and get it operational. I have been using it now for a couple weeks with no issue.

Prerequisite: Make sure you have [HACS](https://hacs.xyz/) installed on your Home Assistant. (This step has nothing to do with this repo)

To install this paperless custom integration:
First go to the HACS panel
<img width="126" alt="image" src="https://user-images.githubusercontent.com/86419/195141400-05e7d908-9eaf-4847-80ec-7007d4389ae6.png">
Select "Integrations"
<img width="616" alt="image" src="https://user-images.githubusercontent.com/86419/195141501-69926153-871e-408c-affd-0a2f747604da.png">
Use the triple dot menu at the top right to select custom repositories
<img width="848" alt="image" src="https://user-images.githubusercontent.com/86419/195141639-e4a22c07-3975-48b7-829c-11fdd64f342e.png">
Enter `https://github.com/ItsEcholot/ha-paperless-ng-sensor/` as the Repository and select `Integration` for Category and Add it.
You should see it in the list
<img width="454" alt="image" src="https://user-images.githubusercontent.com/86419/195142010-e8ede6b0-2892-4384-b754-fb4170f0cfe0.png">

Now close the custom repositories pop up and select "Explore and Download Repositories" button at the bottom right
<img width="360" alt="image" src="https://user-images.githubusercontent.com/86419/195142190-0bfd79f0-9966-4ca5-ad99-a2ce3b24039c.png">

Search for Paperless and install the integration and follow the config flow to authenticate with your paperless server. (Sorry I can not post screenshots of that as I don't want to uninstall the integration and reset all my automations)

Hope that helps!

**Comment by ItsEcholot** [comment]
@L-E-0-N Do you still need help with this?

**Comment by L-E-0-N** [comment]
No, thanks a lot @Ionshard for the explanation. Afterward I tried to incorporate Paperless without any integration and found the REST sensors to be working exactly as I wanted. Still loving the integration but any chance I get to be less dependent on integrations are a plus.
